name: rag-application
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyter
  - pip
  - pip:
      - langchain
      - langchain-classic
      - langchain-chroma
      - langchain-openai
      - langchain-community
      - langchain-text-splitters
      - pypdf
      - tree-sitter
      - tree-sitter-languages
      - langchain-core
      - python-dotenv
      - GitPython
      - pandas
